# Generated by Django 5.0.7 on 2024-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок блога')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое блога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/image', verbose_name='Превью / Изображение')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('sign_of_publication', models.BooleanField(verbose_name='Признак публикации')),
                ('views_counter', models.IntegerField(verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
