# Generated by Django 5.0.7 on 2024-08-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
