# Generated by Django 5.0.7 on 2024-08-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image_alter_blog_sign_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/image/', verbose_name='Превью / Изображение'),
        ),
    ]
